// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Infrastructure.Persistence;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20250901054003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(3979),
                            Description = "Laptop Gamer",
                            Name = "Laptop Gamer",
                            Price = 1500m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(3984)
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(4586),
                            Description = "Laptop Gamer",
                            Name = "Teclado Mecánico",
                            Price = 100m,
                            Stock = 200,
                            UpdatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(4586)
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(4587),
                            Description = "Laptop Gamer",
                            Name = "Mouse Inalámbrico",
                            Price = 50m,
                            Stock = 25,
                            UpdatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(4588)
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(4588),
                            Description = "Monitor Gamer",
                            Name = "Monitor Gamer",
                            Price = 50m,
                            Stock = 25,
                            UpdatedAt = new DateTime(2025, 9, 1, 5, 40, 0, 820, DateTimeKind.Utc).AddTicks(4589)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
